/**
 * camera_system.c
 * Five Nights at Epstein - TI-84 CE Port
 * Ported from CameraSystem.js
 *
 * All setTimeout chains replaced with tick-accumulator state machines.
 * All DOM/HTML replaced with gfx_ draw calls.
 * All audio removed.
 * Static video replaced with random noise drawn on the back buffer.
 * Lightning eyes effect (Night 6) replaced with a simple cyan pixel
 * scatter drawn on top of the EP sprite.
 */

#include <string.h>
#include <stdlib.h>
#include <stdio.h>
#include <graphx.h>

#include "camera_system.h"
#include "game.h"
#include "game_state.h"
#include "enemy_ai.h"
#include "ui_manager.h"

/* =========================================================
 * SPRITE EXTERNS
 * Generated by convimg from assets/convimg.yaml
 * ========================================================= */
extern gfx_sprite_t *spr_map;          /* FNAE-Map-layout.png, 320x240 */
extern gfx_sprite_t *spr_cam[12];      /* spr_cam[1..11], 320x240 each */
extern gfx_sprite_t *spr_ep[12];       /* EP sprites per cam index      */
extern gfx_sprite_t *spr_ep_n6[12];    /* Night 6 EP sprites            */
extern gfx_sprite_t *spr_trump[12];    /* Trump sprites per cam index   */
extern gfx_sprite_t *spr_hawking;      /* mrstephen.png                 */

/* =========================================================
 * CAMERA MAP POSITIONS
 * Derived from JS cameraPositions array (percentages → pixels
 * on 320×240).  Formula: pixel = pct * dim / 100.
 * ========================================================= */
static const CamMapPos CAM_MAP_POSITIONS[] = {
    { 1,  CAM_1,  82,  202, 42, 19 },
    { 2,  CAM_2,  112, 136, 42, 19 },
    { 3,  CAM_3,  165, 186, 42, 19 },
    { 4,  CAM_4,  185, 108, 41, 19 },
    { 5,  CAM_5,  241, 145, 41, 19 },
    { 6,  CAM_6,  247, 197, 42, 19 },
    { 7,  CAM_7,  166,  67, 41, 19 },
    { 8,  CAM_8,  257,  53, 41, 19 },
    { 9,  CAM_9,  78,   49, 41, 19 },
    { 10, CAM_10, 25,   94, 41, 19 },
    { 11, CAM_11, 233,  11, 42, 19 },
};
#define N_CAMS  (sizeof(CAM_MAP_POSITIONS) / sizeof(CAM_MAP_POSITIONS[0]))

/* YOU marker position on the map */
#define YOU_X  22
#define YOU_Y  198
#define YOU_W  42
#define YOU_H  19

/* =========================================================
 * STATIC NOISE DRAW  (replaces <video> static effect)
 * ========================================================= */
static void draw_static_noise(void) {
    for (int y = 0; y < LCD_H; y += 4) {
        for (int x = 0; x < LCD_W; x += 4) {
            if (rand() & 1) {
                gfx_SetColor((rand() & 1) ? 1 : 0);
                gfx_SetPixel(x + (rand() & 3), y + (rand() & 3));
            }
        }
    }
}

/* =========================================================
 * INIT / RESET
 * ========================================================= */
void camera_system_init(CameraSystem *cs, struct Game *game) {
    memset(cs, 0, sizeof(CameraSystem));
    cs->game = game;
}

void camera_system_reset(CameraSystem *cs) {
    cs->trans_phase       = CAM_TRANS_IDLE;
    cs->trans_tick_accum  = 0;
    cs->restart_phase     = CAM_RESTART_IDLE;
    cs->restart_tick_accum = 0;
    cs->lure_state        = LURE_READY;
    cs->lure_tick_accum   = 0;
    cs->sound_use_count   = 0;
    cs->sound_toggle      = 0;
    cs->shock_trans_active = false;
    cs->shock_tick_accum  = 0;
    cs->showing_failure   = false;
    cs->last_ep_location  = CAM_COUNT;
    memset(cs->location_attract_count, 0, sizeof(cs->location_attract_count));
}

/* =========================================================
 * OPEN / CLOSE / TOGGLE
 * ========================================================= */
void camera_system_open(CameraSystem *cs) {
    cs->game->state.camera_open = true;
    cs->game->is_rotating_left  = false;
    cs->game->is_rotating_right = false;

    if (cs->game->state.camera_failed) {
        cs->showing_failure = true;
    } else {
        cs->showing_failure = false;
        camera_system_update_character_display(cs);
    }
}

void camera_system_close(CameraSystem *cs) {
    cs->game->state.camera_open = false;
    cs->showing_failure         = false;
    cs->trans_phase             = CAM_TRANS_IDLE;
}

void camera_system_toggle(CameraSystem *cs) {
    if (cs->game->state.camera_open) {
        camera_system_close(cs);
    } else {
        camera_system_open(cs);
    }
}

/* =========================================================
 * TRANSITION STATE MACHINE  (replaces all setTimeout chains)
 *
 * Used by: switchCamera, playMovementTransition,
 *          playAttractionTransition
 *
 * Phase sequence:
 *   IDLE → STATIC_IN (500 ms) → UPDATE → STATIC_OUT (500 ms) → DONE → IDLE
 * ========================================================= */
static void start_transition(CameraSystem *cs, CamID new_cam, bool is_switch) {
    if (cs->trans_phase != CAM_TRANS_IDLE) return;
    cs->trans_phase      = CAM_TRANS_STATIC_IN;
    cs->trans_tick_accum = 0;
    cs->pending_cam      = new_cam;
    cs->trans_is_switch  = is_switch;
}

static void transition_update(CameraSystem *cs, uint32_t dt) {
    if (cs->trans_phase == CAM_TRANS_IDLE) return;

    cs->trans_tick_accum += dt;

    switch (cs->trans_phase) {
        case CAM_TRANS_STATIC_IN:
            if (cs->trans_tick_accum >= CAM_TRANS_STATIC_TICKS) {
                cs->trans_tick_accum = 0;
                cs->trans_phase = CAM_TRANS_UPDATE;

                /* If failed mid-transition, stay in failure mode */
                if (cs->game->state.camera_failed) {
                    cs->showing_failure = true;
                    cs->trans_phase = CAM_TRANS_IDLE;
                    return;
                }

                /* Apply the pending switch */
                if (cs->trans_is_switch && cs->pending_cam != CAM_COUNT) {
                    cs->game->state.current_cam = cs->pending_cam;
                }
                camera_system_update_character_display(cs);
            }
            break;

        case CAM_TRANS_UPDATE:
            /* Single-frame state — immediately advance */
            cs->trans_phase      = CAM_TRANS_STATIC_OUT;
            cs->trans_tick_accum = 0;
            break;

        case CAM_TRANS_STATIC_OUT:
            if (cs->trans_tick_accum >= CAM_TRANS_STATIC_TICKS) {
                if (cs->game->state.camera_failed) {
                    cs->showing_failure = true;
                }
                cs->trans_phase = CAM_TRANS_IDLE;
            }
            break;

        default:
            cs->trans_phase = CAM_TRANS_IDLE;
            break;
    }
}

/* =========================================================
 * SWITCH CAMERA  (replaces switchCamera(camNum))
 * ========================================================= */
void camera_system_switch(CameraSystem *cs, CamID cam) {
    if (cs->game->state.camera_failed) return;
    if (cs->trans_phase != CAM_TRANS_IDLE) return;
    start_transition(cs, cam, true);
}

/* =========================================================
 * MOVEMENT / ATTRACTION TRANSITION
 * ========================================================= */
void camera_system_play_movement_transition(CameraSystem *cs) {
    if (cs->game->state.camera_failed) return;
    start_transition(cs, CAM_COUNT, false);
}

/* =========================================================
 * CAMERA FAILURE DISPLAY
 * ========================================================= */
void camera_system_show_failure(CameraSystem *cs) {
    cs->showing_failure  = true;
    cs->trans_phase      = CAM_TRANS_IDLE;
}

/* =========================================================
 * RESTART CAMERA  (replaces restartCamera())
 * 4-second countdown then clear failed state.
 * ========================================================= */
void camera_system_restart(CameraSystem *cs) {
    if (cs->game->state.control_panel_busy) return;
    if (cs->restart_phase != CAM_RESTART_IDLE) return;

    cs->game->state.camera_restarting  = true;
    cs->game->state.control_panel_busy = true;
    cs->restart_phase      = CAM_RESTART_WAITING;
    cs->restart_tick_accum = 0;
}

static void restart_update(CameraSystem *cs, uint32_t dt) {
    if (cs->restart_phase != CAM_RESTART_WAITING) return;

    cs->restart_tick_accum += dt;
    if (cs->restart_tick_accum >= CAM_RESTART_TICKS) {
        cs->game->state.camera_failed      = false;
        cs->game->state.camera_restarting  = false;
        cs->game->state.control_panel_busy = false;
        cs->showing_failure                = false;
        cs->restart_phase                  = CAM_RESTART_IDLE;
        camera_system_reset_sound_count(cs);

        if (cs->game->state.camera_open) {
            camera_system_update_character_display(cs);
        }
    }
}

/* =========================================================
 * SOUND LURE  (replaces playAmbientSound())
 * No actual audio on CE — pure game logic.
 * ========================================================= */
void camera_system_play_sound_lure(CameraSystem *cs) {
    if (cs->lure_state == LURE_COOLDOWN) return;

    CamID current_cam = cs->game->state.current_cam;

    /* Reset per-location counts if EP has moved */
    CamID ep_loc = enemy_ai_ep_location(&cs->game->ai);
    if (ep_loc != cs->last_ep_location) {
        memset(cs->location_attract_count, 0,
               sizeof(cs->location_attract_count));
        cs->last_ep_location = ep_loc;
    }

    /* Check if this location is maxed out */
    bool can_attract = (cs->location_attract_count[current_cam] <
                        CAM_MAX_LOCATION_USES);

    bool attracted = false;
    if (can_attract) {
        attracted = enemy_ai_sound_lure(&cs->game->ai, current_cam);
        if (attracted) {
            cs->location_attract_count[current_cam]++;
            cs->last_ep_location = current_cam;
            start_transition(cs, CAM_COUNT, false);
        }
    }

    /* Increment use counter regardless */
    cs->sound_use_count++;
    if (cs->sound_use_count >= CAM_MAX_SOUND_USES) {
        cs->sound_use_count = 0;
        enemy_ai_trigger_camera_failure(&cs->game->ai);
    }

    /* Start cooldown */
    cs->lure_state        = LURE_COOLDOWN;
    cs->lure_tick_accum   = 0;
}

static void lure_cooldown_update(CameraSystem *cs, uint32_t dt) {
    if (cs->lure_state != LURE_COOLDOWN) return;
    cs->lure_tick_accum += dt;
    if (cs->lure_tick_accum >= CAM_LURE_COOLDOWN_TICKS) {
        cs->lure_state      = LURE_READY;
        cs->lure_tick_accum = 0;
    }
}

/* =========================================================
 * SHOCK HAWKING  (replaces shockHawking() in CameraSystem)
 * 1-second static flash then call enemy_ai_shock_hawking().
 * ========================================================= */
static void shock_update(CameraSystem *cs, uint32_t dt) {
    if (!cs->shock_trans_active) return;
    cs->shock_tick_accum += dt;
    if (cs->shock_tick_accum >= CAM_SHOCK_TRANS_TICKS) {
        cs->shock_trans_active = false;
        enemy_ai_shock_hawking(&cs->game->ai);
        camera_system_update_character_display(cs);
    }
}

void camera_system_shock_hawking(CameraSystem *cs) {
    cs->shock_trans_active = true;
    cs->shock_tick_accum   = 0;
}

/* =========================================================
 * RESET SOUND COUNT
 * ========================================================= */
void camera_system_reset_sound_count(CameraSystem *cs) {
    cs->sound_use_count = 0;
}

/* =========================================================
 * UPDATE CHARACTER DISPLAY  (replaces updateCharacterDisplay())
 * No DOM — sets flags that camera_system_draw() reads.
 * The actual sprites are drawn in camera_system_draw().
 * ========================================================= */
void camera_system_update_character_display(CameraSystem *cs) {
    /* Nothing to cache — draw() reads game state directly */
    (void)cs;
}

/* =========================================================
 * MAIN UPDATE  (call every frame from game_run())
 * ========================================================= */
void camera_system_update(CameraSystem *cs, uint32_t dt) {
    transition_update(cs, dt);
    restart_update(cs, dt);
    lure_cooldown_update(cs, dt);
    shock_update(cs, dt);
}

/* =========================================================
 * DRAW CAMERA MAP  (the thumbnail grid view)
 * ========================================================= */
static void draw_camera_map(CameraSystem *cs) {
    /* Map background */
    if (spr_map) {
        gfx_Sprite_NoClip(spr_map, 0, 0);
    } else {
        gfx_FillScreen(COL_BLACK);
    }

    /* YOU marker */
    gfx_SetColor(COL_DARK_GREY);
    gfx_FillRectangle(YOU_X, YOU_Y, YOU_W, YOU_H);
    gfx_SetTextFGColor(COL_WHITE);
    gfx_SetTextScale(1, 1);
    gfx_SetTextXY(YOU_X + 12, YOU_Y + 5);
    gfx_PrintString("YOU");

    /* Camera hotspots */
    for (uint8_t i = 0; i < (uint8_t)N_CAMS; i++) {
        const CamMapPos *p = &CAM_MAP_POSITIONS[i];
        bool selected = (cs->game->state.current_cam == p->cam_id);

        /* Highlight selected camera */
        if (selected) {
            gfx_SetColor(COL_GREEN);
            gfx_DrawRectangle(p->x - 1, p->y - 1, p->w + 2, p->h + 2);
        }

        /* CAM label */
        gfx_SetTextFGColor(selected ? COL_GREEN : COL_WHITE);
        gfx_SetTextScale(1, 1);

        char buf[8];
        snprintf(buf, sizeof(buf), "CAM %u", p->cam_num);
        gfx_SetTextXY(p->x + 2, p->y + 5);
        gfx_PrintString(buf);

        /* Enemy dot indicators on the map */
        CamID ep_loc    = enemy_ai_ep_location(&cs->game->ai);
        CamID trump_loc = enemy_ai_trump_location(&cs->game->ai);

        if (ep_loc == p->cam_id) {
            gfx_SetColor(COL_RED);
            gfx_FillCircle(p->x + p->w - 6, p->y + 4, 3);
        }
        if (trump_loc == p->cam_id) {
            gfx_SetColor(COL_YELLOW);
            gfx_FillCircle(p->x + p->w - 12, p->y + 4, 3);
        }
        /* Hawking dot on CAM 6 */
        if (p->cam_id == CAM_6 &&
            enemy_ai_hawking_warning(&cs->game->ai) > 0) {
            gfx_SetColor(COL_YELLOW);
            gfx_FillCircle(p->x + 4, p->y + 4, 3);
        }
    }
}

/* =========================================================
 * DRAW CAMERA FEED  (the full-screen camera view)
 * ========================================================= */
static void draw_camera_feed(CameraSystem *cs) {
    CamID  cam    = cs->game->state.current_cam;
    uint8_t night = cs->game->state.current_night;

    /* Background sprite for this camera */
    /* spr_cam[] indexed by cam_num (1-11), stored at index cam_num */
    uint8_t cam_idx = 0;
    for (uint8_t i = 0; i < (uint8_t)N_CAMS; i++) {
        if (CAM_MAP_POSITIONS[i].cam_id == cam) {
            cam_idx = CAM_MAP_POSITIONS[i].cam_num;
            break;
        }
    }

    if (cam_idx > 0 && spr_cam[cam_idx]) {
        gfx_Sprite_NoClip(spr_cam[cam_idx], 0, 0);
    } else {
        gfx_FillScreen(COL_DARK_GREY);
    }

    /* --- Hawking at CAM 6 --- */
    if (cam == CAM_6 && spr_hawking) {
        /* Position: left=59.6%, bottom=0.9%, width=37%
         * → x = 191, y = LCD_H - spr_hawking->height - 2       */
        uint16_t hx = 191;
        uint16_t hy = (uint16_t)(LCD_H - spr_hawking->height - 2);
        gfx_TransparentSprite(spr_hawking, hx, hy);
    }

    /* --- Epstein --- */
    CamID ep_loc = enemy_ai_ep_location(&cs->game->ai);
    if (cs->game->ai.epstein.has_spawned && ep_loc == cam) {
        gfx_sprite_t *ep_spr = (night == 6 && spr_ep_n6[cam_idx])
                                ? spr_ep_n6[cam_idx]
                                : spr_ep[cam_idx];
        if (ep_spr) {
            gfx_TransparentSprite(ep_spr, 0, 0);

            /* Night 6: cyan lightning-eye effect (simple pixel dots) */
            if (night == 6) {
                gfx_SetColor(COL_GREEN);   /* cyan approximation in palette */
                for (int dot = 0; dot < 8; dot++) {
                    gfx_SetPixel(ep_spr->width  / 2 + (rand() % 10) - 5,
                                 ep_spr->height / 3 + (rand() % 6)  - 3);
                }
            }
        }
    }

    /* --- Trump (if not crawling) --- */
    CamID trump_loc = enemy_ai_trump_location(&cs->game->ai);
    if (cs->game->ai.trump.has_spawned &&
        !enemy_ai_trump_crawling(&cs->game->ai) &&
        trump_loc == cam &&
        spr_trump[cam_idx]) {
        gfx_TransparentSprite(spr_trump[cam_idx], 0, 0);
    }

    /* --- Current cam label --- */
    char label[10];
    snprintf(label, sizeof(label), "CAM %u", cam_idx);
    gfx_SetTextFGColor(COL_WHITE);
    gfx_SetTextScale(1, 1);
    gfx_SetTextXY(4, 4);
    gfx_PrintString(label);

    /* --- Hawking warning on camera view --- */
    uint8_t hw = enemy_ai_hawking_warning(&cs->game->ai);
    if (hw > 0) {
        ui_manager_draw_hawking_warning(&cs->game->ui, hw);
    }

    /* --- Shock Hawking button (visible at CAM 6, nights 3-5 / custom) --- */
    bool hawk_on = false;
    if (!cs->game->state.custom_night) {
        uint8_t n = night;
        hawk_on = (n >= 3 && n <= 5);
    } else if (cs->game->state.custom_ai.hawking > 0) {
        hawk_on = true;
    }
    if (hawk_on && cam == CAM_6) {
        /* Draw a labelled button at bottom-centre */
        gfx_SetColor(COL_DARK_GREY);
        gfx_FillRectangle(110, LCD_H - 22, 100, 18);
        gfx_SetColor(COL_RED);
        gfx_DrawRectangle(110, LCD_H - 22, 100, 18);
        gfx_SetTextFGColor(COL_RED);
        gfx_SetTextScale(1, 1);
        gfx_SetTextXY(118, LCD_H - 17);
        gfx_PrintString("[ENTER] SHOCK");
    }

    /* --- Lure button (always available, dimmed if on cooldown) --- */
    bool lure_ready = (cs->lure_state == LURE_READY);
    gfx_SetColor(COL_DARK_GREY);
    gfx_FillRectangle(4, LCD_H - 22, 90, 18);
    gfx_SetColor(lure_ready ? COL_WHITE : COL_DIM_WHITE);
    gfx_DrawRectangle(4, LCD_H - 22, 90, 18);
    gfx_SetTextFGColor(lure_ready ? COL_WHITE : COL_DIM_WHITE);
    gfx_SetTextXY(8, LCD_H - 17);
    gfx_PrintString(lure_ready ? "[2nd] LURE" : "[2nd] ...");
}

/* =========================================================
 * DRAW  (top-level, called every frame when camera is open)
 * ========================================================= */
void camera_system_draw(CameraSystem *cs) {
    /* Camera failure: show static noise + ERR */
    if (cs->showing_failure || cs->game->state.camera_failed) {
        draw_static_noise();
        gfx_SetTextFGColor(COL_RED);
        gfx_SetTextScale(3, 3);
        uint8_t err_x = (LCD_W - 3 * 3 * 8) / 2;
        gfx_SetTextXY(err_x, LCD_H / 2 - 12);
        gfx_PrintString("ERR");
        return;
    }

    /* Shock transition: show static */
    if (cs->shock_trans_active) {
        draw_static_noise();
        return;
    }

    /* During switch / movement transition: show static over existing frame */
    bool in_trans = (cs->trans_phase == CAM_TRANS_STATIC_IN ||
                     cs->trans_phase == CAM_TRANS_STATIC_OUT);

    /* Left half: camera map; right half: camera feed
     * On the CE's 320×240 screen we split vertically at x=160.
     * Camera map → left 160px, camera feed → right 160px.
     * This mirrors the web layout where the map and feed are
     * shown simultaneously in the camera panel.              */
    gfx_SetClipRegion(0, 0, 160, LCD_H);
    draw_camera_map(cs);

    gfx_SetClipRegion(160, 0, LCD_W, LCD_H);
    draw_camera_feed(cs);

    gfx_SetClipRegion(0, 0, LCD_W, LCD_H);

    /* Static noise overlay during transitions */
    if (in_trans) {
        draw_static_noise();
    }

    /* Controls hint */
    gfx_SetTextFGColor(COL_DIM_WHITE);
    gfx_SetTextScale(1, 1);
    gfx_SetTextXY(4, LCD_H - 32);
    gfx_PrintString("[LEFT/RIGHT] Cameras  [ALPHA] Close");
}
